version: '3.8'

services:
  sc-platform:
    build: .
    privileged: true
    container_name: sc-platform
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
